services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false       # Allows optimizing the container by removing unused services; this also means
      # fetching services directly from the container via $container->get() won't work.
    # The best practice is to be explicit about your dependencies anyway.

  LogicItLab\Salesforce\MapperBundle\:
    resource: '../../*'
    exclude: '../../{Tests}'

  LogicItLab\Salesforce\MapperBundle\Mapper:
    arguments:
      - '@phpforce.soap_client'
      - '@LogicItLab\Salesforce\MapperBundle\Annotation\AnnotationReader'
      - '@LogicItLab\Salesforce\MapperBundle\Cache\FileCache'

  LogicItLab\Salesforce\MapperBundle\Cache\FileCache:
    arguments:
      - '%kernel.cache_dir%/salesforce'

  LogicItLab\Salesforce\MapperBundle\Annotation\AnnotationReader:
    arguments:
      - '@annotation_reader'

  LogicItLab\Salesforce\MapperBundle\MappedBulkSaver:
    arguments:
      - '@phpforce.soap_client.bulk_saver'
      - '@LogicItLab\Salesforce\MapperBundle\Mapper'
      - '@LogicItLab\Salesforce\MapperBundle\Annotation\AnnotationReader'
